root: true
extends:
  - standard
  - plugin:markdown/recommended
plugins:
  - markdown
parserOptions:
  ecmaVersion: 2021
globals:
  globalThis: readonly
overrides:
  - files: '**/*.md'
    processor: 'markdown/markdown'
