language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.6"
  - "4.0"
  - "4.1"
sudo: false
script:
  - "test $TRAVIS_NODE_VERSION != '0.6' || npm test"
  - "test $TRAVIS_NODE_VERSION  = '0.6' || npm run-script test-travis"
after_script:
  - "test $TRAVIS_NODE_VERSION = '0.10' && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
