/*!
 * content-disposition
 * Copyright(c) 2014-2017 Douglas Christopher Wilson
 * MIT Licensed
 */

export interface ContentDisposition {
  /**
   * Content-Disposition type, such as "attachment" or "inline"
   */
  type: string;
  /**
   * Content-Disposition parameters, such as "filename"
   */
  parameters: Record<string, string>;
}

export interface CreateOptions {
  /**
   * Content-Disposition type, defaults to "attachment"
   * @default "attachment"
   */
  type?: string;
  /**
   * Fallback filename for non-ISO-8859-1 strings. If true, a fallback will be generated by replacing non-latin1 characters with "?". If false, no fallback will be generated.
   * @default true
   */
  fallback?: string | boolean;
}

/**
 * Null object perf optimization. Faster than `Object.create(null)` and `{ __proto__: null }`.
 */
const NullObject = /* @__PURE__ */ (() => {
  const C = function () {};
  C.prototype = Object.create(null);
  return C;
})() as unknown as { new (): any };

/**
 * Create an attachment Content-Disposition header.
 */
export function create(filename?: string, options?: CreateOptions): string {
  const type = options?.type || 'attachment';
  const parameters = createparams(filename, options?.fallback);

  return format({ type, parameters });
}

const SP = 32; // " "
const HTAB = 9; // "\t"
const SEMI = 59; // ";"
const EQ = 61; // "="
const DQUOTE = 34; // '"'
const BSLASH = 92; // "\\"

/**
 * Parse Content-Disposition header string.
 */
export function parse(header: string): ContentDisposition {
  const len = header.length;
  let index = skipOWS(header, 0, header.length);

  const typeStart = index;
  index = parseToken(header, index, len);
  const typeEnd = trailingOWS(header, typeStart, index);
  const type = header.slice(typeStart, typeEnd).toLowerCase();

  const parameters: Record<string, string> = new NullObject();

  parameter: while (index < len) {
    index = skipOWS(header, index + 1, len); // Skip over semicolon.

    const keyStart = index;

    while (index < len) {
      const char = header.charCodeAt(index);
      if (char === SEMI) continue parameter;

      if (char === EQ) {
        const keyEnd = trailingOWS(header, keyStart, index);
        const key = header.slice(keyStart, keyEnd).toLowerCase();

        index = skipOWS(header, index + 1, len);

        if (index < len && header.charCodeAt(index) === DQUOTE) {
          index++;

          let value = '';
          while (index < len) {
            const code = header.charCodeAt(index++);
            if (code === DQUOTE) {
              index = parseToken(header, index, len);
              if (parameters[key] === undefined) parameters[key] = value;
              continue parameter;
            }

            if (code === BSLASH && index < len) {
              value += header[index++];
              continue;
            }

            value += String.fromCharCode(code);
          }
        }

        const valueStart = index;
        index = parseToken(header, index, len);
        const valueEnd = trailingOWS(header, valueStart, index);
        const value = header.slice(valueStart, valueEnd);

        if (key.charCodeAt(key.length - 1) === 42 /* "*" */) {
          const normalizedKey = key.slice(0, -1);
          const decoded = decodeRFC8187(value);
          if (decoded !== undefined) {
            parameters[normalizedKey] = decoded;
            continue parameter;
          }
        }

        if (parameters[key] === undefined) parameters[key] = value;
        continue parameter;
      }

      index++;
    }
  }

  return { type, parameters };
}

/**
 * TextDecoder instance for UTF-8 decoding when decodeURIComponent fails due to invalid byte sequences.
 */
const utf8Decoder = new TextDecoder('utf-8');

/**
 * RegExp to match non attr-char, *after* encodeURIComponent (i.e. not including "%")
 */
const ENCODE_URL_ATTR_CHAR_REGEXP = /[\x00-\x20"'()*,/:;<=>?@[\\\]{}\x7f]/g; // eslint-disable-line no-control-regex

/**
 * RegExp to match non-latin1 characters.
 */
const NON_LATIN1_REGEXP = /[^\x20-\x7e\xa0-\xff]/g;

/**
 * RegExp to match chars that must be quoted-pair in RFC 2616
 */
const QUOTE_REGEXP = /([\\"])/g;

/**
 * RegExp for various RFC 2616 grammar
 *
 * parameter     = token "=" ( token | quoted-string )
 * token         = 1*<any CHAR except CTLs or separators>
 * separators    = "(" | ")" | "<" | ">" | "@"
 *               | "," | ";" | ":" | "\" | <">
 *               | "/" | "[" | "]" | "?" | "="
 *               | "{" | "}" | SP | HT
 * quoted-string = ( <"> *(qdtext | quoted-pair ) <"> )
 * qdtext        = <any TEXT except <">>
 * quoted-pair   = "\" CHAR
 * CHAR          = <any US-ASCII character (octets 0 - 127)>
 * TEXT          = <any OCTET except CTLs, but including LWS>
 * LWS           = [CRLF] 1*( SP | HT )
 * CRLF          = CR LF
 * CR            = <US-ASCII CR, carriage return (13)>
 * LF            = <US-ASCII LF, linefeed (10)>
 * SP            = <US-ASCII SP, space (32)>
 * HT            = <US-ASCII HT, horizontal-tab (9)>
 * CTL           = <any US-ASCII control character (octets 0 - 31) and DEL (127)>
 * OCTET         = <any 8-bit sequence of data>
 */
const TEXT_REGEXP = /^[\x20-\x7e\x80-\xff]+$/;
const TOKEN_REGEXP = /^[!#$%&'*+.0-9A-Z^_`a-z|~-]+$/;

/**
 * Create parameters object from filename and fallback.
 */
function createparams(
  filename?: string,
  fallback: string | boolean = true,
): Record<string, string> | undefined {
  if (filename === undefined) {
    return;
  }

  if (typeof filename !== 'string') {
    throw new TypeError('filename must be a string');
  }

  if (typeof fallback !== 'string' && typeof fallback !== 'boolean') {
    throw new TypeError('fallback must be a string or boolean');
  }

  if (typeof fallback === 'string' && NON_LATIN1_REGEXP.test(fallback)) {
    throw new TypeError('fallback must be ISO-8859-1 string');
  }

  const params: Record<string, string> = new NullObject();

  // restrict to file base name
  const name = basename(filename);

  // determine if name is suitable for quoted string
  const isQuotedString = TEXT_REGEXP.test(name);

  // generate fallback name
  const fallbackName =
    typeof fallback !== 'string'
      ? fallback && getlatin1(name)
      : basename(fallback);
  const hasFallback = typeof fallbackName === 'string' && fallbackName !== name;

  // set extended filename parameter
  if (hasFallback || !isQuotedString || hasHexEscape(name)) {
    params['filename*'] = name;
  }

  // set filename parameter
  if (isQuotedString || hasFallback) {
    params.filename = hasFallback ? fallbackName : name;
  }

  return params;
}

/**
 * Decode a RFC 8187 field value (gracefully).
 */
function decodeRFC8187(str: string): string | undefined {
  const charsetEnd = str.indexOf("'");
  if (charsetEnd <= 0) {
    return undefined;
  }

  const languageEnd = str.indexOf("'", charsetEnd + 1);
  if (languageEnd === -1) {
    return undefined;
  }

  const charset = str.slice(0, charsetEnd).toLowerCase();
  const encoded = str.slice(languageEnd + 1);

  switch (charset) {
    case 'iso-8859-1': {
      const binary = decodeHexEscapes(encoded);
      return getlatin1(binary);
    }
    case 'utf-8':
    case 'utf8': {
      try {
        return decodeURIComponent(encoded);
      } catch {
        // Failed to decode with decodeURIComponent, fallback to lenient decoding which replaces invalid UTF-8 byte sequences with the Unicode replacement character
        // TODO: Consider removing in the next major version to be more strict about invalid percent-encodings
        const binary = decodeHexEscapes(encoded);

        const bytes = new Uint8Array(binary.length);
        for (let idx = 0; idx < binary.length; idx++) {
          bytes[idx] = binary.charCodeAt(idx);
        }

        return utf8Decoder.decode(bytes);
      }
    }
  }

  return undefined;
}

/**
 * Parse a token starting at the provided index.
 */
function parseToken(str: string, index: number, len: number): number {
  while (index < len) {
    const char = str.charCodeAt(index);
    if (char === SEMI) break;
    index++;
  }
  return index;
}

/**
 * Skip RFC 2616 linear whitespace (space / tab).
 */
function skipOWS(str: string, index: number, len: number): number {
  while (index < len) {
    const char = str.charCodeAt(index);
    if (char !== SP && char !== HTAB) break;
    index++;
  }
  return index;
}

/**
 * Skip RFC 2616 linear whitespace (space / tab) from the end of a string.
 */
function trailingOWS(str: string, start: number, end: number): number {
  while (end > start) {
    const char = str.charCodeAt(end - 1);
    if (char !== SP && char !== HTAB) break;
    end--;
  }
  return end;
}

/**
 * Format object to Content-Disposition header.
 */
function format(obj: Partial<ContentDisposition>): string {
  if (!obj || typeof obj !== 'object') {
    throw new TypeError('argument obj is required');
  }

  if (
    !obj.type ||
    typeof obj.type !== 'string' ||
    !TOKEN_REGEXP.test(obj.type)
  ) {
    throw new TypeError('invalid type');
  }

  // start with normalized type
  let string = obj.type.toLowerCase();

  // append parameters
  if (obj.parameters && typeof obj.parameters === 'object') {
    const params = Object.keys(obj.parameters).sort();

    for (let i = 0; i < params.length; i++) {
      const param = params[i];

      const val =
        param.slice(-1) === '*'
          ? ustring(obj.parameters[param])
          : qstring(obj.parameters[param]);

      string += `; ${param}=${val}`;
    }
  }

  return string;
}

/**
 * Get ISO-8859-1 version of string.
 */
function getlatin1(val: string): string {
  // simple Unicode -> ISO-8859-1 transformation
  return val.replace(NON_LATIN1_REGEXP, '?');
}

/**
 * Percent encode a single character.
 */
function pencode(char: string): string {
  return '%' + char.charCodeAt(0).toString(16).toUpperCase();
}

/**
 * Quote a string for HTTP.
 */
function qstring(val: unknown): string {
  const str = String(val);

  return '"' + str.replace(QUOTE_REGEXP, '\\$1') + '"';
}

/**
 * Encode a Unicode string for HTTP (RFC 5987).
 */
function ustring(val: unknown): string {
  const str = String(val);

  // percent encode as UTF-8
  const encoded = encodeURIComponent(str).replace(
    ENCODE_URL_ATTR_CHAR_REGEXP,
    pencode,
  );

  return "UTF-8''" + encoded;
}

/**
 * Return the last portion of a path
 */
function basename(path: string): string {
  const normalized = path.replaceAll('\\', '/');

  let end = normalized.length;
  while (end > 0 && normalized[end - 1] === '/') {
    end--;
  }

  if (end === 0) {
    return '';
  }

  let start = end - 1;
  while (start >= 0 && normalized[start] !== '/') {
    start--;
  }

  return normalized.slice(start + 1, end);
}

/**
 * Check if a character is a hex digit [0-9A-Fa-f]
 */
function isHexDigit(char: string): boolean {
  const code = char.charCodeAt(0);
  return (
    (code >= 48 && code <= 57) || // 0-9
    (code >= 65 && code <= 70) || // A-F
    (code >= 97 && code <= 102) // a-f
  );
}

/**
 * Check if a string contains percent encoding escapes.
 */
function hasHexEscape(str: string): boolean {
  const maxIndex = str.length - 3;
  let lastIndex = -1;

  while (
    (lastIndex = str.indexOf('%', lastIndex + 1)) !== -1 &&
    lastIndex <= maxIndex
  ) {
    if (isHexDigit(str[lastIndex + 1]) && isHexDigit(str[lastIndex + 2])) {
      return true;
    }
  }

  return false;
}

/**
 * Decode hex escapes in a string (e.g., %20 -> space)
 */
function decodeHexEscapes(str: string): string {
  const firstEscape = str.indexOf('%');
  if (firstEscape === -1) return str;

  let result = str.slice(0, firstEscape);
  for (let idx = firstEscape; idx < str.length; idx++) {
    if (
      str[idx] === '%' &&
      idx + 2 < str.length &&
      isHexDigit(str[idx + 1]) &&
      isHexDigit(str[idx + 2])
    ) {
      result += String.fromCharCode(
        Number.parseInt(str[idx + 1] + str[idx + 2], 16),
      );
      idx += 2;
    } else {
      result += str[idx];
    }
  }
  return result;
}
