/*!
 * content-disposition
 * Copyright(c) 2014-2017 Douglas Christopher Wilson
 * MIT Licensed
 */

export interface ContentDisposition {
  /**
   * Content-Disposition type, such as "attachment" or "inline"
   */
  type: string;
  /**
   * Content-Disposition parameters, such as "filename"
   */
  parameters: Record<string, string>;
}

export interface CreateOptions {
  /**
   * Content-Disposition type, defaults to "attachment"
   * @default "attachment"
   */
  type?: string;
  /**
   * Fallback filename for non-ISO-8859-1 strings. If true, a fallback will be generated by replacing non-latin1 characters with "?". If false, no fallback will be generated.
   * @default true
   */
  fallback?: string | boolean;
}

/**
 * Null object perf optimization. Faster than `Object.create(null)` and `{ __proto__: null }`.
 */
const NullObject = /* @__PURE__ */ (() => {
  const C = function () {};
  C.prototype = Object.create(null);
  return C;
})() as unknown as { new (): any };

/**
 * Create an attachment Content-Disposition header.
 */
export function create(filename?: string, options?: CreateOptions): string {
  const type = options?.type || 'attachment';
  const parameters = createparams(filename, options?.fallback);

  return format({ type, parameters });
}

/**
 * Parse Content-Disposition header string.
 */
export function parse(string: string): ContentDisposition {
  if (!string || typeof string !== 'string') {
    throw new TypeError('argument string is required');
  }

  let index = 0;
  const typeEnd = parseToken(string, index);
  if (typeEnd === -1) {
    throw new TypeError('invalid type format');
  }

  const type = string.slice(index, typeEnd).toLowerCase();
  index = skipLinearWhitespace(string, typeEnd);

  if (index < string.length && string[index] !== ';') {
    throw new TypeError('invalid type format');
  }

  const parameters: Record<string, string> = new NullObject();
  const names = new Set<string>();

  while (index < string.length) {
    if (string[index] !== ';') {
      throw new TypeError('invalid parameter format');
    }

    index = skipLinearWhitespace(string, index + 1);

    const keyStart = index;
    const keyEnd = parseToken(string, index);
    if (keyEnd === -1) {
      throw new TypeError('invalid parameter format');
    }

    index = skipLinearWhitespace(string, keyEnd);

    if (index >= string.length || string[index] !== '=') {
      throw new TypeError('invalid parameter format');
    }

    index = skipLinearWhitespace(string, index + 1);

    let value: string;
    let isQuoted = false;
    if (index < string.length && string[index] === '"') {
      const parsedQuoted = parseQuotedString(string, index);
      value = parsedQuoted.value;
      index = parsedQuoted.index;
      isQuoted = true;
    } else {
      const valueEnd = parseToken(string, index);
      if (valueEnd === -1) {
        throw new TypeError('invalid parameter format');
      }

      value = string.slice(index, valueEnd);
      index = valueEnd;
    }

    index = skipLinearWhitespace(string, index);

    let key = string.slice(keyStart, keyEnd).toLowerCase();
    if (names.has(key)) {
      throw new TypeError('invalid duplicate parameter');
    }

    names.add(key);

    if (key.indexOf('*') + 1 === key.length) {
      if (isQuoted) {
        throw new TypeError('invalid extended field value');
      }

      // decode extended value
      key = key.slice(0, -1);
      value = decodefield(value);

      // overwrite existing value
      parameters[key] = value;
      continue;
    }

    if (typeof parameters[key] === 'string') {
      continue;
    }

    parameters[key] = value;
  }

  return { type, parameters };
}

/**
 * TextDecoder instance for UTF-8 decoding when decodeURIComponent fails due to invalid byte sequences.
 */
const utf8Decoder = new TextDecoder('utf-8');

/**
 * RegExp to match non attr-char, *after* encodeURIComponent (i.e. not including "%")
 */
const ENCODE_URL_ATTR_CHAR_REGEXP = /[\x00-\x20"'()*,/:;<=>?@[\\\]{}\x7f]/g; // eslint-disable-line no-control-regex

/**
 * RegExp to match non-latin1 characters.
 */
const NON_LATIN1_REGEXP = /[^\x20-\x7e\xa0-\xff]/g;

/**
 * RegExp to match chars that must be quoted-pair in RFC 2616
 */
const QUOTE_REGEXP = /([\\"])/g;

/**
 * RegExp for various RFC 2616 grammar
 *
 * parameter     = token "=" ( token | quoted-string )
 * token         = 1*<any CHAR except CTLs or separators>
 * separators    = "(" | ")" | "<" | ">" | "@"
 *               | "," | ";" | ":" | "\" | <">
 *               | "/" | "[" | "]" | "?" | "="
 *               | "{" | "}" | SP | HT
 * quoted-string = ( <"> *(qdtext | quoted-pair ) <"> )
 * qdtext        = <any TEXT except <">>
 * quoted-pair   = "\" CHAR
 * CHAR          = <any US-ASCII character (octets 0 - 127)>
 * TEXT          = <any OCTET except CTLs, but including LWS>
 * LWS           = [CRLF] 1*( SP | HT )
 * CRLF          = CR LF
 * CR            = <US-ASCII CR, carriage return (13)>
 * LF            = <US-ASCII LF, linefeed (10)>
 * SP            = <US-ASCII SP, space (32)>
 * HT            = <US-ASCII HT, horizontal-tab (9)>
 * CTL           = <any US-ASCII control character (octets 0 - 31) and DEL (127)>
 * OCTET         = <any 8-bit sequence of data>
 */
const TEXT_REGEXP = /^[\x20-\x7e\x80-\xff]+$/;
const TOKEN_REGEXP = /^[!#$%&'*+.0-9A-Z^_`a-z|~-]+$/;

/**
 * Create parameters object from filename and fallback.
 */
function createparams(
  filename?: string,
  fallback: string | boolean = true,
): Record<string, string> | undefined {
  if (filename === undefined) {
    return;
  }

  if (typeof filename !== 'string') {
    throw new TypeError('filename must be a string');
  }

  if (typeof fallback !== 'string' && typeof fallback !== 'boolean') {
    throw new TypeError('fallback must be a string or boolean');
  }

  if (typeof fallback === 'string' && NON_LATIN1_REGEXP.test(fallback)) {
    throw new TypeError('fallback must be ISO-8859-1 string');
  }

  const params: Record<string, string> = new NullObject();

  // restrict to file base name
  const name = basename(filename);

  // determine if name is suitable for quoted string
  const isQuotedString = TEXT_REGEXP.test(name);

  // generate fallback name
  const fallbackName =
    typeof fallback !== 'string'
      ? fallback && getlatin1(name)
      : basename(fallback);
  const hasFallback = typeof fallbackName === 'string' && fallbackName !== name;

  // set extended filename parameter
  if (hasFallback || !isQuotedString || hasHexEscape(name)) {
    params['filename*'] = name;
  }

  // set filename parameter
  if (isQuotedString || hasFallback) {
    params.filename = hasFallback ? fallbackName : name;
  }

  return params;
}

/**
 * Decode a RFC 5987 field value (gracefully).
 */
function decodefield(str: string): string {
  const charsetEnd = str.indexOf("'");
  if (charsetEnd <= 0) {
    throw new TypeError('invalid extended field value');
  }

  const languageEnd = str.indexOf("'", charsetEnd + 1);
  if (languageEnd === -1) {
    throw new TypeError('invalid extended field value');
  }

  const charset = str.slice(0, charsetEnd);
  const language = str.slice(charsetEnd + 1, languageEnd);
  const encoded = str.slice(languageEnd + 1);

  if (
    !isMimeCharset(charset) ||
    !isLanguageTag(language) ||
    !isExtendedValueChars(encoded)
  ) {
    throw new TypeError('invalid extended field value');
  }

  const normalizedCharset = charset.toLowerCase();

  switch (normalizedCharset) {
    case 'iso-8859-1': {
      const binary = decodeHexEscapes(encoded);
      return getlatin1(binary);
    }
    case 'utf-8':
    case 'utf8': {
      try {
        return decodeURIComponent(encoded);
      } catch {
        // Failed to decode with decodeURIComponent, fallback to lenient decoding which replaces invalid UTF-8 byte sequences with the Unicode replacement character
        // TODO: Consider removing in the next major version to be more strict about invalid percent-encodings
        const binary = decodeHexEscapes(encoded);

        const bytes = new Uint8Array(binary.length);
        for (let idx = 0; idx < binary.length; idx++) {
          bytes[idx] = binary.charCodeAt(idx);
        }

        return utf8Decoder.decode(bytes);
      }
    }
  }

  throw new TypeError('unsupported charset in extended field');
}

/**
 * Parse a token starting at the provided index.
 */
function parseToken(str: string, index: number): number {
  let end = index;

  while (end < str.length && isTokenChar(str[end])) {
    end++;
  }

  return end === index ? -1 : end;
}

/**
 * Parse a quoted string starting at the provided index.
 */
function parseQuotedString(
  str: string,
  index: number,
): { value: string; index: number } {
  let result = '';
  let cursor = index + 1;

  while (cursor < str.length) {
    const char = str[cursor];

    if (char === '"') {
      return { value: result, index: cursor + 1 };
    }

    if (char === '\\') {
      cursor++;

      if (cursor >= str.length || !isQuotedPairChar(str[cursor])) {
        throw new TypeError('invalid parameter format');
      }

      result += str[cursor];
      cursor++;
      continue;
    }

    if (!isQuotedTextChar(char)) {
      throw new TypeError('invalid parameter format');
    }

    result += char;
    cursor++;
  }

  throw new TypeError('invalid parameter format');
}

/**
 * Skip RFC 2616 linear whitespace (space / tab).
 */
function skipLinearWhitespace(str: string, index: number): number {
  while (index < str.length && isLinearWhitespace(str[index])) {
    index++;
  }

  return index;
}

/**
 * Format object to Content-Disposition header.
 */
function format(obj: Partial<ContentDisposition>): string {
  if (!obj || typeof obj !== 'object') {
    throw new TypeError('argument obj is required');
  }

  if (
    !obj.type ||
    typeof obj.type !== 'string' ||
    !TOKEN_REGEXP.test(obj.type)
  ) {
    throw new TypeError('invalid type');
  }

  // start with normalized type
  let string = obj.type.toLowerCase();

  // append parameters
  if (obj.parameters && typeof obj.parameters === 'object') {
    const params = Object.keys(obj.parameters).sort();

    for (let i = 0; i < params.length; i++) {
      const param = params[i];

      const val =
        param.slice(-1) === '*'
          ? ustring(obj.parameters[param])
          : qstring(obj.parameters[param]);

      string += `; ${param}=${val}`;
    }
  }

  return string;
}

/**
 * Get ISO-8859-1 version of string.
 */
function getlatin1(val: string): string {
  // simple Unicode -> ISO-8859-1 transformation
  return val.replace(NON_LATIN1_REGEXP, '?');
}

/**
 * Percent encode a single character.
 */
function pencode(char: string): string {
  return '%' + char.charCodeAt(0).toString(16).toUpperCase();
}

/**
 * Quote a string for HTTP.
 */
function qstring(val: unknown): string {
  const str = String(val);

  return '"' + str.replace(QUOTE_REGEXP, '\\$1') + '"';
}

/**
 * Encode a Unicode string for HTTP (RFC 5987).
 */
function ustring(val: unknown): string {
  const str = String(val);

  // percent encode as UTF-8
  const encoded = encodeURIComponent(str).replace(
    ENCODE_URL_ATTR_CHAR_REGEXP,
    pencode,
  );

  return "UTF-8''" + encoded;
}

/**
 * Return the last portion of a path
 */
function basename(path: string): string {
  const normalized = path.replaceAll('\\', '/');

  let end = normalized.length;
  while (end > 0 && normalized[end - 1] === '/') {
    end--;
  }

  if (end === 0) {
    return '';
  }

  let start = end - 1;
  while (start >= 0 && normalized[start] !== '/') {
    start--;
  }

  return normalized.slice(start + 1, end);
}

/**
 * Check if a character is RFC 2616 linear whitespace.
 */
function isLinearWhitespace(char: string): boolean {
  return char === ' ' || char === '\t';
}

/**
 * Check if a character is valid in a token.
 */
function isTokenChar(char: string): boolean {
  const code = char.charCodeAt(0);

  return (
    isAlphaNumericCode(code) ||
    char === '!' ||
    char === '#' ||
    char === '$' ||
    char === '%' ||
    char === '&' ||
    char === "'" ||
    char === '*' ||
    char === '+' ||
    char === '.' ||
    char === '^' ||
    char === '_' ||
    char === '`' ||
    char === '|' ||
    char === '~' ||
    char === '-'
  );
}

/**
 * Check if a character is allowed directly inside a quoted string.
 */
function isQuotedTextChar(char: string): boolean {
  const code = char.charCodeAt(0);

  return (
    (code >= 0x20 && code <= 0x21) ||
    (code >= 0x23 && code <= 0x5b) ||
    (code >= 0x5d && code <= 0x7e) ||
    (code >= 0x80 && code <= 0xff)
  );
}

/**
 * Check if a character is valid after a quoted-pair escape.
 */
function isQuotedPairChar(char: string): boolean {
  const code = char.charCodeAt(0);
  return code >= 0x20 && code <= 0x7e;
}

/**
 * Check if a string is a valid MIME charset token.
 */
function isMimeCharset(str: string): boolean {
  if (str.length === 0) {
    return false;
  }

  for (let index = 0; index < str.length; index++) {
    const char = str[index];
    const code = char.charCodeAt(0);

    if (
      !isAlphaNumericCode(code) &&
      char !== '!' &&
      char !== '#' &&
      char !== '$' &&
      char !== '%' &&
      char !== '&' &&
      char !== '+' &&
      char !== '-' &&
      char !== '^' &&
      char !== '_' &&
      char !== '`' &&
      char !== '{' &&
      char !== '}' &&
      char !== '~'
    ) {
      return false;
    }
  }

  return true;
}

/**
 * Check if a string looks like a RFC 5646 language tag.
 */
function isLanguageTag(str: string): boolean {
  if (str.length === 0) {
    return true;
  }

  let segmentLength = 0;

  for (let index = 0; index < str.length; index++) {
    const char = str[index];

    if (char === '-') {
      if (segmentLength === 0) {
        return false;
      }

      segmentLength = 0;
      continue;
    }

    if (!isAlphaCode(char.charCodeAt(0))) {
      return false;
    }

    segmentLength++;
  }

  return segmentLength > 0;
}

/**
 * Check if a string contains only RFC 5987 value-chars.
 */
function isExtendedValueChars(str: string): boolean {
  if (str.length === 0) {
    return false;
  }

  for (let index = 0; index < str.length; index++) {
    const char = str[index];
    const code = char.charCodeAt(0);

    if (char === '%') {
      if (
        index + 2 >= str.length ||
        !isHexDigit(str[index + 1]) ||
        !isHexDigit(str[index + 2])
      ) {
        return false;
      }

      index += 2;
      continue;
    }

    if (
      !isAlphaNumericCode(code) &&
      char !== '!' &&
      char !== '#' &&
      char !== '$' &&
      char !== '&' &&
      char !== '+' &&
      char !== '.' &&
      char !== '^' &&
      char !== '_' &&
      char !== '`' &&
      char !== '|' &&
      char !== '~' &&
      char !== '-'
    ) {
      return false;
    }
  }

  return true;
}

/**
 * Check if a character code is alphabetic.
 */
function isAlphaCode(code: number): boolean {
  return (
    (code >= 65 && code <= 90) || // A-Z
    (code >= 97 && code <= 122) // a-z
  );
}

/**
 * Check if a character code is alphanumeric.
 */
function isAlphaNumericCode(code: number): boolean {
  return isAlphaCode(code) || (code >= 48 && code <= 57);
}

/**
 * Check if a character is a hex digit [0-9A-Fa-f]
 */
function isHexDigit(char: string): boolean {
  const code = char.charCodeAt(0);
  return (
    (code >= 48 && code <= 57) || // 0-9
    (code >= 65 && code <= 70) || // A-F
    (code >= 97 && code <= 102) // a-f
  );
}

/**
 * Check if a string contains percent encoding escapes.
 */
function hasHexEscape(str: string): boolean {
  const maxIndex = str.length - 3;
  let lastIndex = -1;

  while (
    (lastIndex = str.indexOf('%', lastIndex + 1)) !== -1 &&
    lastIndex <= maxIndex
  ) {
    if (isHexDigit(str[lastIndex + 1]) && isHexDigit(str[lastIndex + 2])) {
      return true;
    }
  }

  return false;
}

/**
 * Decode hex escapes in a string (e.g., %20 -> space)
 */
function decodeHexEscapes(str: string): string {
  const firstEscape = str.indexOf('%');
  if (firstEscape === -1) return str;

  let result = str.slice(0, firstEscape);
  for (let idx = firstEscape; idx < str.length; idx++) {
    if (
      str[idx] === '%' &&
      idx + 2 < str.length &&
      isHexDigit(str[idx + 1]) &&
      isHexDigit(str[idx + 2])
    ) {
      result += String.fromCharCode(
        Number.parseInt(str[idx + 1] + str[idx + 2], 16),
      );
      idx += 2;
    } else {
      result += str[idx];
    }
  }
  return result;
}
